/*
 * Station configuration — edit this file to change the station.
 * Loaded before app.js; exposes window.STATION_CONFIG.
 *
 * SOURCE MODES
 *   (a) "videos":   an explicit list of YouTube video IDs (you control order + track notes)
 *   (b) "playlist": a regular YouTube playlist ID (starts with PL…, OL…, UU…, etc.)
 *                   loaded via the IFrame API's loadPlaylist / listType 'playlist'.
 *                   Do NOT use auto-generated Mix lists (RD…) — they are per-viewer and unstable.
 */
window.STATION_CONFIG = {
  station: {
    name: "Hardcore",
    // EDITABLE: tagline shown under the station name
    tagline: "The hardest stuff out there. Nonstop.",
    logoText: "HC",             // shown in the round logo badge (or set logoImage)
    logoImage: "",              // e.g. "assets/logo.png" — overrides logoText when set
  },

  // Use youtube-nocookie.com (privacy-enhanced embed). Still the official IFrame API.
  privacyEnhancedMode: false,

  source: {
    type: "videos",             // "videos" | "playlist"
    playlistId: "",             // used when type === "playlist", e.g. "PLxxxxxxxxxxxxxxxx"
    loop: true,                 // after the last track, start the list again (true = nonstop radio, false = stop)
  },

  // Track list for "videos" mode. title/channel are optional: if omitted, the site uses
  // track-meta.js (generated by tools/fetch_titles.py via YouTube oEmbed), then falls
  // back to player.getVideoData() at runtime.
  tracks: [
    {
      id: "dnhqZcG0tew",
      title: "",
      channel: "",
      // EDITABLE track note (sources: see README "Track note sources")
      notes:
        "Recorded where rap rarely goes: live outside the White House at the Million Mask March on November 5, 2013. That's the annual Guy Fawkes Day protest tied to the hacktivist collective Anonymous, where crowds show up in V for Vendetta masks. Steve Grant wrote the words, and the music is credited to Courtney Driver. The title comes from the Book of Revelation, where the opening of the seventh seal starts the end times, and Grant pitches the moment as that kind of turning point. Over three verses he casts rappers, hackers, activists and \"infowarriors\" as one awakened movement pushing back against what he describes as threatened freedoms, media deception and a collapsing \"new world order.\" The hook is a chant about seeing through the lies and not being afraid. It's raw protest rap, crowd noise and all: the artist's manifesto, delivered at street level.",
    },
    {
      id: "1yOoM7_AseY",
      title: "",
      channel: "",
      // EDITABLE track note (sources: see README "Track note sources")
      notes:
        "Two members of New York's underground Stronghold crew, back to back. Poison Pen (Lékan Herron) is a Bed-Stuy, Brooklyn battle MC who came up through the late-'90s NYC battle circuit, including the Blaze Battle, and went on to host Da Cypha Emcee Battles. Immortal Technique (Felipe Coronel) was born in Lima, Peru, and raised in Harlem. He's the fiercely independent voice behind Revolutionary Vol. 1 and 2. The track comes from Pen's 2009 album The Money Shot, and Pen's part opens by congratulating the newly elected President Obama before telling him hands off his guns. The song is the artists' case for armed self-defense, aimed at a state and police they say won't protect their neighborhoods. Technique ties it to the arms trade, Gaza and the barbarian sacks of Rome. Pen points to Haiti and to the revolution America was founded on. Reviews of the album singled it out as a standout.",
    },
    {
      id: "ZbiMp6VqYYg",
      title: "Dr. Dre - For The Love Of Money (feat. Jill Scott, Jon Connor & Anderson .Paak)",
      channel: "",
      // EDITABLE track note (sources: see README "Track note sources")
      notes:
        "Dr. Dre's 2015 album Compton was his first in 16 years, after 2001 (1999). He put it together after scrapping the long-promised Detox, inspired by working on the N.W.A biopic Straight Outta Compton. This is track 12, produced by Cardiak. Jill Scott sings the hook, Flint, Michigan rapper Jon Connor and Dre trade verses, and Anderson .Paak takes the bridge. The opening chant nods to Bone Thugs-n-Harmony and Eazy-E's \"Foe Tha Love Of $,\" and the beat borrows from a 1977 song by Italian prog-rock band Locanda delle Fate. Connor raps for his hometown and his block, while Dre plays the guy in all black at the party who came from the bottom anyway. Under all the flexing, the hook keeps calling money the root of all evil, and the bridge warns that money will never be faithful to you.",
    },
    {
      id: "T9CHWOsGrx0",
      title: "",
      channel: "",
      // EDITABLE track note (sources: see README "Track note sources")
      notes:
        "The first full song on Compton, right after the intro. This official lyric video comes from Dr. Dre's VEVO channel. Dre gives the first and last verses to King Mez, and Justus sings a hook about one day having everything, borrowing \"it was all a dream\" from the Notorious B.I.G.'s \"Juicy.\" In his own verse, Dre runs through his history: selling instrumentals by pager, becoming a millionaire before the headphones (a nod to Beats), and sitting on Eminem checks he still hasn't opened. He jokes that he's too old to remember he already has it all. Mez plays the hungry newcomer linked up with a legend, and takes shots at emotional, heartbroken rap. Compton debuted at No. 2 on the Billboard 200 with 295,000 units in its first week.",
    },
    {
      id: "DiWM-f1uRQg",
      title: "",
      channel: "",
      // EDITABLE track note (sources: see README "Track note sources")
      notes:
        "A heavyweight posse cut from 2012. The Goondox are hip-hop veteran PMD (half of EPMD), New York hardcore rapper Sean Strange and the European production crew Snowgoons, and this track comes from their album Welcome to the Goondox. Snowgoons made the beat, and Sean Strange and Bundy handle the chorus. The guest list is massive: Swollen Members (Madchild and Prevail), Jus Allah, Impakt, ODoub, Klee Magor, Virtuoso, Meth Mouth, Psych Ward and Jaysaun, all passing the mic one after another. There's no message here beyond dominance: battle-axes, comic-book and mythological boasts, horror-movie gore and open threats, in the classic battle-rap tradition. Reel Wolf Productions shot the video, Tom Vujcic directed it, and Klee Magor came up with the title. Pure hardcore.",
    },
    {
      id: "h8Rf24KdOBw",
      title: "",
      channel: "",
      // EDITABLE track note (sources: see README "Track note sources")
      notes:
        "K-Rino is a Houston underground pioneer from the South Park neighborhood. He started rapping in 1983 and founded the South Park Coalition crew in 1987. He has stayed independent his whole career, releasing his music on his own Black Book International label. This is the title track of his 2010 double album Annihilation of the Evil Machine (29 tracks, about two hours), produced by 5-7 Red. It's six minutes of sci-fi storytelling. A mystic and two visitors tell K-Rino he was chosen to destroy a machine that pumps lies into the masses through governments, media and the airwaves. He battles a robot with a screen for a head and blows it up, only to watch it split into countless offspring. K-Rino has said a comic-book version of the story is in the works. This video is a fan-made upload, not an official one.",
    },
  ],

  // Track notes for "playlist" mode, keyed by video ID (optional).
  playlistNotes: {
    // "VIDEO_ID": "Your note about this track…",
  },

  // EDITABLE: About-the-station text
  about: [
    "Hardcore is an independent web station for the hardest stuff out there: rap and protest music with something to say and the force to say it. Every track is hand-picked by Blake and streamed through YouTube's official player, so the artists keep their views.",
    "Each track comes with our own notes on who made it and what it's about. The views in the songs belong to the artists. Got something heavier for the rotation? Get in touch."
  ],
};
