/*
 * Station configuration — edit this file to change the station.
 * Loaded before app.js; exposes window.STATION_CONFIG.
 *
 * SOURCE MODES
 *   (a) "videos":   an explicit list of YouTube video IDs (you control order + track notes)
 *   (b) "playlist": a regular YouTube playlist ID (starts with PL…, OL…, UU…, etc.)
 *                   loaded via the IFrame API's loadPlaylist / listType 'playlist'.
 *                   Do NOT use auto-generated Mix lists (RD…) — they are per-viewer and unstable.
 */
window.STATION_CONFIG = {
  station: {
    name: "Hardcore",
    // EDITABLE: tagline shown under the station name
    tagline: "The hardest stuff out there. Nonstop.",
    logoText: "HC",             // shown in the round logo badge (or set logoImage)
    logoImage: "",              // e.g. "assets/logo.png" — overrides logoText when set
  },

  // Use youtube-nocookie.com (privacy-enhanced embed). Still the official IFrame API.
  privacyEnhancedMode: false,

  source: {
    type: "videos",             // "videos" | "playlist"
    playlistId: "",             // used when type === "playlist", e.g. "PLxxxxxxxxxxxxxxxx"
    loop: true,                 // after the last track, start the list again (true = nonstop radio, false = stop)
  },

  // Track list for "videos" mode. title/channel are optional: if omitted, the site uses
  // track-meta.js (generated by tools/fetch_titles.py via YouTube oEmbed), then falls
  // back to player.getVideoData() at runtime.
  tracks: [
    {
      id: "dnhqZcG0tew",
      title: "",
      channel: "",
      // EDITABLE track note (sources: see README "Track note sources")
      notes:
        "Recorded where rap rarely goes: live outside the White House at the Million Mask March on November 5, 2013. That's the annual Guy Fawkes Day protest tied to the hacktivist collective Anonymous, where crowds show up in V for Vendetta masks. Steve Grant wrote the words, and the music is credited to Courtney Driver. The title comes from the Book of Revelation, where the opening of the seventh seal starts the end times, and Grant pitches the moment as that kind of turning point. Over three verses he casts rappers, hackers, activists and \"infowarriors\" as one awakened movement pushing back against what he describes as threatened freedoms, media deception and a collapsing \"new world order.\" The hook is a chant about seeing through the lies and not being afraid. It's raw protest rap, crowd noise and all: the artist's manifesto, delivered at street level.",
    },
    {
      id: "1yOoM7_AseY",
      title: "",
      channel: "",
      // EDITABLE track note (sources: see README "Track note sources")
      notes:
        "Two members of New York's underground Stronghold crew, back to back. Poison Pen (Lékan Herron) is a Bed-Stuy, Brooklyn battle MC who came up through the late-'90s NYC battle circuit, including the Blaze Battle, and went on to host Da Cypha Emcee Battles. Immortal Technique (Felipe Coronel) was born in Lima, Peru, and raised in Harlem. He's the fiercely independent voice behind Revolutionary Vol. 1 and 2. The track comes from Pen's 2009 album The Money Shot, and Pen's part opens by congratulating the newly elected President Obama before telling him hands off his guns. The song is the artists' case for armed self-defense, aimed at a state and police they say won't protect their neighborhoods. Technique ties it to the arms trade, Gaza and the barbarian sacks of Rome. Pen points to Haiti and to the revolution America was founded on. Reviews of the album singled it out as a standout.",
    },
    // ---- Added from a snapshot of YouTube Mix RDfwqSqLRPe0g (2026-10-02). EDITABLE notes. ----
    {
      id: "fwqSqLRPe0g",
      title: "",
      channel: "",
      notes:
        "The seed track of this set. Alais Clay is a bilingual conscious-hip-hop artist, born in Barranquilla, Colombia, raised in Miami, and now based between Costa Rica and Colorado. Here she trades verses with GhostRyder and Steve Grant on a song from her album End of an Era, which came out on December 21, 2014 and was offered as a free download. Steve Grant's The Seventh Seal is already on the station. The title says it all: break loose.",
    },
    {
      id: "azOvjLmbd4s",
      title: "",
      channel: "",
      notes:
        "Alais Clay recorded this in 2021 and dropped the video on October 31, 2022. She wrote the lyrics, performed the vocals, and directed and edited the video herself. It cuts in news clips from 2020 to 2022, and three \"peaceful dissenters\" wear CV dazzle face paint, a camouflage style first designed to fool facial recognition. In the description, Clay says the point is to raise awareness of what she sees as a growing surveillance and control grid built in the name of health and safety.",
    },
    {
      id: "UBV-avF9P-E",
      title: "",
      channel: "",
      notes:
        "Track 5 from Alais Clay's 2014 album End of an Era, a record she dedicated to her \"superhero family\" around the globe. The title borrows the old idea that pressure turns coal into diamonds, and the song fits the album's arc of turning hardship into strength. The album was mixed and mastered by Stephen Caputo at Durty Mics Studios, the same Florida studio behind much of Steve Grant's catalog.",
    },
    {
      id: "OvouxUrZbRo",
      title: "",
      channel: "",
      notes:
        "One of the heaviest songs in the rotation, and not for the reason you'd think. Track 3 from Alais Clay's 2020 EP Resurfacing [Part I] is, in her words, about releasing the stored energy of sexual trauma, whether personal or inherited, and reclaiming power afterward. She frames it as a healing song for anyone who has lived through that pain. Instrumental by Matthew Norrish Jacobson, mixed and mastered by Stephen Caputo. The video carries a trigger warning.",
    },
    {
      id: "L9kBJrGA6wI",
      title: "",
      channel: "",
      notes:
        "An early link-up between Alais Clay and Steve Grant, released in 2013 ahead of her album End of an Era. Recorded, mixed and filmed at Durty Mics Studio and directed by Stephen Caputo and Grant. The lyrics paint society as a dark circus run by unseen puppet masters. They name schools, screens, GMOs, wireless radiation, psychiatric labels and medication as tools of control, and a hook that dismisses the red-team/blue-team split as one machine. Those are the artists' views, delivered at full force.",
    },
    {
      id: "u7SfFRQjMFY",
      title: "",
      channel: "",
      notes:
        "ODD TV is a self-described \"truth seeker\" rapper, producer and content creator. On this 2016 upload he's joined by Payday Monsanto. The title comes from John Carpenter's 1988 cult film They Live, where hidden rulers keep the public asleep, In a 2022 note on his channel, ODD TV wrote that some of his videos had been taken down and one of his releases pulled from streaming services.",
    },
    {
      id: "_PdigNCB--g",
      title: "",
      channel: "",
      notes:
        "Released November 22, 2024. Alais Clay and DISL Automatic, two longtime collaborators in the conscious-rap underground, call it a call for unity against everything they see working to divide people. The lyrics and vocals are by both artists. The track was mixed at JBC Studios in Cartagena, Colombia, on an instrumental by Don P, and filmed by DOA Photography. It's one of the newest cuts on the station, and one of the most hopeful.",
    },
    {
      id: "5Q6oqPuzA5k",
      title: "",
      channel: "",
      notes:
        "Track 3 from End of an Era. Alais Clay wrote it, performed it and edited the video, and JeeJuh Productions made the beat. She raps with urgency, like time is running out, casting herself as an escaped \"renegade slave\" who came back to tell the story. She calls herself non-compliant and not for sale, takes aim at mainstream media, apathy and a materialistic, profit-first culture, and asks how the masses can be woken up before things collapse.",
    },
    {
      id: "YNpR4TjVPtc",
      title: "",
      channel: "",
      notes:
        "From Reverse Hypnosis, the debut album Alais Clay released on 11.11.11, four years after she started recording and performing. That record introduced her mix of rap, reggae and activist themes. This official video for track 6 came out in 2015. Since then Clay has shared stages with KRS-One, Immortal Technique, Ziggy Marley and members of the Wu-Tang Clan, according to her official bio.",
    },
    {
      id: "2rz7Sh_qDq8",
      title: "",
      channel: "",
      notes:
        "Steve Grant's 2013 plea to the bystanders. The title echoes Martin Luther King Jr.'s Letter from Birmingham Jail, which warned about \"the appalling silence of the good people,\" and Grant invokes King directly. He asks what happened to the peace people once kept with each other, blames screens for numbing everyone, and explains why he steps on stage masked. The hook is aimed at listeners who would rather look away than face what he calls the truth. Music by Danson, produced at Durty Mics Studios.",
    },
    {
      id: "aKzBEahGgb8",
      title: "",
      channel: "",
      notes:
        "Steve Grant dedicates this one to the fallen members of what he calls the Anonymous Million Mask March family. He wrote the lyrics over a Hala X beat, and it was mixed and filmed by Stephen Caputo at Durty Mics. It's a look back at a movement: being caged and breaking out, the courage it took, the lives lost along the way. The hook tells listeners to never forget who they are. The song first appeared on his channel in 2015, and this video version followed on Guy Fawkes Day 2018.",
    },
    {
      id: "sAWG5rdS5D8",
      title: "",
      channel: "",
      notes:
        "DISL Automatic calls himself a \"truth hop\" MC, and his \"Get BIG On 'Em\" brand doubles as a plant-based fitness and vegan-lifestyle project. This 2014 video comes from his free Get BIG On 'Em!!! mixtape. The beat is by VeCity, the producer behind many of DISL's early videos, and the video was shot by DoA Al Omer. Three minutes of pure push.",
    },
    {
      id: "jUAzGRh6eQ4",
      title: "",
      channel: "",
      notes:
        "An early DISL Automatic video from December 2013, produced by VeCity. It came out around the time of his debut mixtape, Power To The People Vol. 1, which he gave away free on his site. The title is a statement of persistence, from an MC whose catalog is built on refusing to fold. It was later added to Spotify, so it has outlived a lot of its 2013 peers.",
    },
    {
      id: "MRMXifWfHVg",
      title: "",
      channel: "",
      notes:
        "Another ODD TV cut, uploaded in July 2018 and billed by the artist as \"truth music,\" the tag that underground conspiracy-minded rap uses for itself. ODD TV describes himself as a truth seeker, rapper and producer, and the title argues that things could be different. A short, factual note, because there's little independent information about this track beyond the artist's own channel.",
    },
    {
      id: "bab_07mBKqI",
      title: "",
      channel: "",
      notes:
        "Released July 7, 2017 as the first single from Alais Clay's next album. She wrote and sang it, and came up with the concept and the edit. Justin Bilancieri filmed it, Totem mixed it, and The Legion made the instrumental. It's a rebel anthem about numbers: she says there are too many people waking up to silence them all, and the hook is about dragging the \"vampires\" of empire into the light. Torches up, curtain raised.",
    },
    {
      id: "M3Wh1mNdTJY",
      title: "",
      channel: "",
      notes:
        "Track 4 from Alais Clay's End of an Era, which she offered as a free download or for a donation through her site. Clay wrote the lyrics, performed the vocals and edited the video, and Stephen Caputo of Durty Mics Studios mixed and mastered it. The title is literal. Like most of her catalog, the song is built around getting a message across, not around flexing.",
    },
    {
      id: "Cxk0YaN8lWc",
      title: "",
      channel: "",
      notes:
        "Steve Grant in battle-rap mode. This 2015 video was shot in Hollywood, Florida, over a beat by Allrounda and mixed by Stephen Caputo. Instead of protest slogans he stacks comic-book villains into his boasts, from Galactus and Thanos to Carnage, and brags about a flow dark enough to swallow light. It's a reminder that the Anonymous-scene MC can simply rap, too.",
    },
    {
      id: "MN708_EhVNM",
      title: "",
      channel: "",
      notes:
        "A music video that doubles as a documentary. It was filmed in the streets of Miami during the March Against Monsanto on May 24, 2014, part of a worldwide day of protest against the agrochemical giant and GMOs. Steve Grant raps in an Anonymous mask and refuses to stay quiet. He calls out the Trans-Pacific Partnership trade deal and squares off with police over free speech. Beat by Ronnie Romerce, mixed by Stephen Caputo.",
    },
    {
      id: "tCWravEFb5U",
      title: "",
      channel: "",
      notes:
        "Billed as an anthem: Mr Matty Moses featuring ODD TV, uploaded in July 2018. \"We do not consent\" is a slogan heard across anti-authority protest movements, and the track turns it into a two-and-a-half-minute chant of refusal. Little else about this release can be verified beyond the upload itself, so this note stays short.",
    },
    {
      id: "XYiGsNkJlHA",
      title: "",
      channel: "",
      notes:
        "Released December 4, 2024. Alais Clay links up with Chances R Good on an instrumental by Gradozero, mixed at JBC Studios in Cartagena. Instead of protest, this one goes cosmic. It starts back when we were vibrations and stardust, calls people miracles, and mourns lost ancient knowledge and forgotten languages. It asks for \"fierce compassion\" for a world that is both sacred and painful. Waking up, in her telling, starts with wonder.",
    },
    {
      id: "SvPlrwV6wl4",
      title: "",
      channel: "",
      notes:
        "DISL Automatic did almost everything himself on this 2021 single: he wrote, performed, recorded and mixed the vocals. The title uses \"Babylon\" the way reggae and conscious rap have for decades, as shorthand for a corrupt system, and calls for it to burn. It's on Spotify and was offered as a free download on SoundCloud, in keeping with DISL's habit of giving his music away.",
    },
    {
      id: "5mft2RfXjjw",
      title: "",
      channel: "",
      notes:
        "A 2014 posse cut: DISL Automatic with fellow underground MCs Genocide and Beast 1333. In his verse, DISL says knowledge beats fashion and he isn't flashing diamonds or cars. He talks about planning to wake people up and take it to the streets, and points to history: empires rise, and every elite that thought it was untouchable fell. The hook's claim is that together they can't be stopped.",
    },
    {
      id: "HtyTBQ1PklM",
      title: "",
      channel: "",
      notes:
        "Power Through People (PTP) featuring Steve Grant. This 2014 video was the single from PTP's album Firestorm of Discussion. In the description, PTP says it's time to open our minds to the corrupt system people live in, and that the revolution starts with improving yourself. Filmed by Sky Jones, edited by Rory Gallagher, produced by Kevin Blazie. The title plays on the old \"his story\" pun on history.",
    },
    {
      id: "Q0ZMCsqDa8c",
      title: "",
      channel: "",
      notes:
        "Steve Grant and Atom Warlok go all-in on November 5th. They wear custom Guy Fawkes masks and open with Gunpowder Plot jokes, and Grant raps that he wakes up every day like it's Guy Fawkes Night. The lyrics present Anonymous as a \"legion\" that hugs you one minute and shouts down the system the next. They end with an openly anarchist \"no rulers, no masters\" line. That's the artists' stance. Mixed by Stephen Caputo, beat by ThatKidGoran, released in 2017.",
    },
    {
      id: "v8R254Bno5I",
      title: "",
      channel: "",
      notes:
        "Track 2 from Alais Clay's album Elevated Frequencies, released December 21, 2017. The video premiered in August 2018. It's a march song, cut with footage from Standing Rock solidarity marches in Toronto and New York, a water-rights march in Detroit, the Million Mask March in D.C., WTO protests and environmental marches in South America. There's also live footage from her album release party at Cervantes in Denver. Totem mixed it and played flute, and Blanq Beats made the beat.",
    },
    {
      id: "vVmY0SVQ_ps",
      title: "",
      channel: "",
      notes:
        "A change of pace: Alais Clay and Maiyu Ondaro call this a \"new paradigm love song.\" Both artists wrote and sang it, Danson made the instrumental, and Stephen Caputo mixed and mastered it at Durty Mics Studios. The artwork is by Brett Jones, who also did the cover of End of an Era. It was released in 2016 as a duet, and proof that a hard-edged station can make room for something tender.",
    },
    {
      id: "VkASGroP-Ko",
      title: "",
      channel: "",
      notes:
        "One of the oldest videos in this set: a fan upload from December 2011, shared by a friend of Alais Clay as \"revolutionary words to awaken the people.\" She raps it with McAD of Freedom Movement, a collaborator she'd return to years later on Home to Roost and The Legend of Johnny Hurley. The title is a promise not to be silenced, and it set the tone for her catalog.",
    },
    {
      id: "Ry9fvLSf6Hw",
      title: "",
      channel: "",
      notes:
        "GhostRyder featuring Steve Grant and DISL Automatic, from 2014. The video was produced by Grant's home base, Durty Mics Studio. All three rappers move in the same independent, activist-rap circle, and GhostRyder also appears with Grant on Alais Clay's Cut The Ties. The title is the message: a three-man pep talk about holding your ground.",
    },
    {
      id: "5G0DBXvoT-Q",
      title: "",
      channel: "",
      notes:
        "An ODD TV video from July 2016, which the artist billed as an \"anti-Illuminati\" music video. The Illuminati, a real Bavarian secret society that was banned in the 1780s, has become shorthand in conspiracy culture for a hidden ruling elite. The title describes humanity under that imagined control. These are the artist's views. Not much about the track can be independently verified.",
    },
    {
      id: "03V187Vu6Mg",
      title: "",
      channel: "",
      notes:
        "A 2020 collaboration between what the description calls \"three freedom-loving individuals.\" Alais Clay takes the first verse and McAD of Freedom Movement the second, and guitarist John Scarlata closes it with a solo. Freedom Movement Productions mixed it on a Thomas Hodek instrumental. The title is the old proverb about chickens coming home to roost, meaning consequences eventually return to whoever set them in motion.",
    },
    {
      id: "j18nnjKK2_w",
      title: "",
      channel: "",
      notes:
        "A tribute to Johnny Hurley (1980-2021). On June 21, 2021 in Olde Town Arvada, Colorado, Hurley confronted and stopped a gunman who had just killed a police officer, and was then fatally shot by a responding officer who mistook him for the shooter. Alais Clay and Freedom Movement, his friends, honor the man and the courage of his last act. The intro samples Hurley himself, and the video was released in October 2023, unmonetized.",
    },
    {
      id: "ibHd0zBJ6ig",
      title: "",
      channel: "",
      notes:
        "From Zeitgeist: The Spirit of the Age, released in 2010 by the Philadelphia underground group The Lost Children of Babylon. Their label describes the group's lyrics as philosophical, occult and conspiracy-themed, and Wikipedia says the album centers on the New World Order and the Illuminati. Martial Law features Rasul Allah, Jon Murdock, Lex Starwind, Atun Sen Geb and Cosmic Crusader. It's a dense, nearly seven-minute posse cut. The views are the group's own.",
    },
    {
      id: "uRGZIEPWCnc",
      title: "",
      channel: "",
      notes:
        "A 2017 summit of the scene: Power Through People with Steve Grant and Alais Clay. The description also credits Derrick Broze of The Conscious Resistance, and the beat is by Anno Domini. Grant's vocals were recorded at Durty Mic Studios by Stephen Caputo. The title says what all these artists keep saying in different ways: the status quo has to go, and ordinary people are the ones who'll change it.",
    },
    {
      id: "lssYt05BO8I",
      title: "",
      channel: "",
      notes:
        "DISL Automatic, December 2014, over a VeCity beat. The title sounds like a beef record, but for DISL the target is a whole system rather than one rival rapper. It comes from the free Get BIG On 'Em mixtape and is now also on Spotify. Short and sharp, and a good entry point to his early work.",
    },
    {
      id: "BhXZPcIZ6SM",
      title: "",
      channel: "",
      notes:
        "Anilyst released Triple Threat as a single on January 30, 2012, and the video followed that February. It's a chest-out underground rap record whose title is a boast about doing it all. It's here because the YouTube Mix this set was built from pulled it in alongside the station's protest-rap core. A short, factual note, because there's little independent information about the artist.",
    },
    {
      id: "YBWzv2LZlNQ",
      title: "",
      channel: "",
      notes:
        "DISL Automatic and SinTheSis team up over an Anno Domini beat on this 2016 song from DISL's free project G.E.M.S. The title points to a code of conduct: fighting for what you believe in, but doing it honorably. SinTheSis is one of DISL's go-to collaborators. The two also share the mic with ASpirit on System Reboot, elsewhere in this rotation.",
    },
    {
      id: "qCBYvrXNFR0",
      title: "",
      channel: "",
      notes:
        "DISL Automatic, SinTheSis and ASpirit, produced by VeCity, from 2014. The hook frames revolution in computer terms: a \"system reboot,\" control-alt-delete, with the people taking the planet back. The three MCs pass the mic, each pushing the same idea that ordinary people can force a hard restart on a broken system. It's a staple of the GlobalFaction channel, which also hosted DISL's early videos.",
    },
    {
      id: "7LTomMX3eWA",
      title: "",
      channel: "",
      notes:
        "Steve Grant pulls in Alais Clay, Heidi D and DISL Automatic for a December 2016 call to action. Grant's opening verse is about moving from talk to marching, and asks how anyone can stand up for their beliefs while sitting down. He also references Jade Helm 15, the 2015 U.S. military training exercise that became a magnet for conspiracy theories. The message is that nobody does it alone: show up, and the rest follows.",
    },
    {
      id: "s6ZpswGUZnY",
      title: "",
      channel: "",
      notes:
        "CRUCIFIX featuring Credit. The track was written by both artists and produced by Bobby Ruckuss, with a 2012 copyright under Cruce Signati, which is Latin for \"signed with the cross.\" The video, directed by CRUCIFIX with PhiveMedia, followed in 2014. The title suggests a song about confession and course correction. Not much more about this release could be verified, so this note stays short.",
    },
    {
      id: "9sq7m38KWmM",
      title: "",
      channel: "",
      notes:
        "The YouTube title spells out the thesis, but the song's actual name is The Ambush, from DISL Automatic's free mixtape Power to the People. This lyric video was made by Urban Mentality and posted in November 2016, the week of the U.S. presidential election. The song lays out DISL's view that elected leaders are puppets of deeper financial and corporate power. In the description he links documentaries such as The Corporation and Naomi Klein's The Shock Doctrine as starting points for further research.",
    },
    {
      id: "oAiAdhv_6Hw",
      title: "",
      channel: "",
      notes:
        "From Payday Monsanto's 2013 album Missiles With Relish, a sprawling independent release that came out on January 28, 2013 through CD Baby. The title is the gun-rights movement's term for politicians who push firearm restrictions, which tells you which side of that debate this song is on. It's the artist's stance. Payday Monsanto also features on ODD TV's They Live, We Sleep, elsewhere in the rotation.",
    },
    {
      id: "lS8UfEe3N6o",
      title: "",
      channel: "",
      notes:
        "Drezus (Jeremiah Manitopyes) is a Plains Cree rapper and activist from Calgary with roots in the Muskowekwan and Cote First Nations. He came up through the Cree hip-hop collective War Party and Team Rezofficial, and won several Indigenous Music Awards for his 2014 album Indian Summer. In 2017 he shared an MTV VMA with Taboo for a Standing Rock anthem. Get Up! (2017) was the first single from his album Public Enemy: a stomping call to rise, directed by Stuey Kubrick.",
    },
    {
      id: "GKnxsLDsfZ0",
      title: "",
      channel: "",
      notes:
        "Power Through People, Steve Grant and DISL Automatic on one track, from June 2016. The beat is by 2Deep, and it was mixed and mastered by Stephen Caputo. The title casts ordinary people as giants. PTP offered the song as a free download, which is common in this scene, where most of these artists give their music away to spread the message.",
    },
  ],

  // Track notes for "playlist" mode, keyed by video ID (optional).
  playlistNotes: {
    // "VIDEO_ID": "Your note about this track…",
  },

  // EDITABLE: About-the-station text
  about: [
    "Hardcore is an independent web station for the hardest stuff out there: rap and protest music with something to say and the force to say it. Every track is hand-picked by Blake and streamed through YouTube's official player, so the artists keep their views.",
    "Each track comes with our own notes on who made it and what it's about. The views in the songs belong to the artists. Got something heavier for the rotation? Get in touch."
  ],
};
