/*
 * Station configuration — edit this file to change the station.
 * Loaded before app.js; exposes window.STATION_CONFIG.
 *
 * SOURCE MODES
 *   (a) "videos":   an explicit list of YouTube video IDs (you control order + track notes)
 *   (b) "playlist": a regular YouTube playlist ID (starts with PL…, OL…, UU…, etc.)
 *                   loaded via the IFrame API's loadPlaylist / listType 'playlist'.
 *                   Do NOT use auto-generated Mix lists (RD…) — they are per-viewer and unstable.
 */
window.STATION_CONFIG = {
  station: {
    name: "Hardcore",
    // EDITABLE: tagline shown under the station name
    tagline: "The hardest stuff out there. Nonstop.",
    logoText: "HC",             // shown in the round logo badge (or set logoImage)
    logoImage: "",              // e.g. "assets/logo.png" — overrides logoText when set
  },

  // Use youtube-nocookie.com (privacy-enhanced embed). Still the official IFrame API.
  privacyEnhancedMode: false,

  source: {
    type: "videos",             // "videos" | "playlist"
    playlistId: "",             // used when type === "playlist", e.g. "PLxxxxxxxxxxxxxxxx"
    loop: true,                 // after the last track, start the list again (true = nonstop radio, false = stop)
  },

  // Track list for "videos" mode. title/channel are optional: if omitted, the site uses
  // track-meta.js (generated by tools/fetch_titles.py via YouTube oEmbed), then falls
  // back to player.getVideoData() at runtime.
  tracks: [
    {
      id: "dnhqZcG0tew",
      title: "",
      channel: "",
      notes:
        "Placeholder track note. Write a few original sentences here about why this track is " +
        "on the station: the artist, the mood, where you first heard it, what to listen for. " +
        "Original commentary like this is what makes the site more than a page of embeds.",
    },
    {
      id: "1yOoM7_AseY",
      title: "",
      channel: "",
      // EDITABLE: placeholder note
      notes:
        "Placeholder track note. Replace with a few original sentences about this track: who made it, " +
        "why it hits as hard as it does, and what to listen for.",
    },
  ],

  // Track notes for "playlist" mode, keyed by video ID (optional).
  playlistNotes: {
    // "VIDEO_ID": "Your note about this track…",
  },

  // EDITABLE: placeholder About-the-station text. Replace with Blake's own words.
  about: [
    "Hardcore plays the hardest stuff out there, picked by hand by Blake. " +
      "Every track streams through YouTube's official embedded player, so artists keep their views.",
    "Each track gets a short note on why it made the cut. Got something heavier? Get in touch.",
  ],
};
