/* Generated by tools/fetch_titles.py from YouTube oEmbed. Do not edit by hand. */
window.TRACK_META = {
  "dnhqZcG0tew": {
    "title": "Steve Grant - The Seventh Seal(Million Mask March)",
    "channel": "Steve Grant",
    "channelUrl": "https://www.youtube.com/@stevegrant8805"
  },
  "1yOoM7_AseY": {
    "title": "The 2nd Ammendment feat. Immortal Technique",
    "channel": "Poison Pen - Topic",
    "channelUrl": "https://www.youtube.com/channel/UCQ81HlRNBAtB3ZyaVAtz_gg"
  },
  "ZbiMp6VqYYg": {
    "title": "For The Love Of Money",
    "channel": "Dr. Dre - Topic",
    "channelUrl": "https://www.youtube.com/channel/UC1g7JmTw4Gv8W9YINg3M1FA"
  },
  "T9CHWOsGrx0": {
    "title": "Dr. Dre - Talk About It (Lyric Video) ft. King Mez, Justus",
    "channel": "DrDreVEVO",
    "channelUrl": "https://www.youtube.com/@DrDreVEVO"
  },
  "DiWM-f1uRQg": {
    "title": "Goondox (PMD & Sean Strange) - Raps Of The Titans ft Swollen Members & more (Prod by Snowgoons)",
    "channel": "Snowgoons",
    "channelUrl": "https://www.youtube.com/@snowgoons"
  },
  "h8Rf24KdOBw": {
    "title": "K-Rino - Annihilation of the Evil Machine (Video)",
    "channel": "TCC",
    "channelUrl": "https://www.youtube.com/@TheColorfulCube"
  },
  "AW77gFdSALE": {
    "title": "Genocide Ft. Vinnie Paz - Conspiracy Of Silence [Prod By: Junior Makhno]",
    "channel": "GenocideRap",
    "channelUrl": "https://www.youtube.com/@GenocideRap"
  },
  "ZP6lxNdNTQQ": {
    "title": "Tom MacDonald - \"The Government\"",
    "channel": "Tom MacDonald",
    "channelUrl": "https://www.youtube.com/@TomMacDonaldOfficial"
  },
  "N1iUN-J-lSs": {
    "title": "Aesop Rock - Drums On The Wheel (Official Video)",
    "channel": "Rhymesayers Entertainment",
    "channelUrl": "https://www.youtube.com/@rhymesayers"
  },
  "tauuueQvTf0": {
    "title": "Xzibit - Shut Yo Mouth ft. Compton AV & Butch Cassidy (Official Video)",
    "channel": "Xzibit",
    "channelUrl": "https://www.youtube.com/@xzibit"
  },
  "VMXUvaaDdwo": {
    "title": "Army of the Pharaohs \"Terrorstorm\" - Official Video",
    "channel": "Vinnie Paz",
    "channelUrl": "https://www.youtube.com/@jmthiphop"
  },
  "91cYRcgu548": {
    "title": "Pete & Bas - Cross Country",
    "channel": "Sindhu World",
    "channelUrl": "https://www.youtube.com/@sindhuworld"
  },
  "kl4wkIPiTcY": {
    "title": "Rage Against The Machine - Sleep Now in the Fire (Official HD Video)",
    "channel": "RATMVEVO",
    "channelUrl": "https://www.youtube.com/@RATMVEVO"
  },
  "sjNLqGSt7dA": {
    "title": "Canon - Round Em Up (Official Audio)",
    "channel": "Reflectionmusicgroup",
    "channelUrl": "https://www.youtube.com/@Reflectionmusicgroup"
  },
  "aMmkNDwnl68": {
    "title": "G-Unit (Album Version (Explicit))",
    "channel": "G-Unit - Topic",
    "channelUrl": "https://www.youtube.com/channel/UCOqyGxp8d02g2pOUEwU4-Rw"
  }
};
