#!/usr/bin/env python3
"""Build step: fetch real titles/channels for every video ID in playlist.js via
YouTube's public oEmbed endpoint and write track-meta.js (window.TRACK_META).

Usage:  python3 tools/fetch_titles.py
Failures are non-fatal; the site falls back to player.getVideoData() at runtime.
"""
import json, re, sys, urllib.request, urllib.parse, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
cfg = (root / "playlist.js").read_text()
# Grab id: "..." entries (11-char YouTube IDs) from the config.
ids = list(dict.fromkeys(re.findall(r'\bid:\s*["\']([A-Za-z0-9_-]{11})["\']', cfg)))
meta = {}
for vid in ids:
    url = "https://www.youtube.com/oembed?" + urllib.parse.urlencode(
        {"url": f"https://www.youtube.com/watch?v={vid}", "format": "json"})
    try:
        with urllib.request.urlopen(url, timeout=15) as r:
            d = json.load(r)
        meta[vid] = {"title": d.get("title", ""), "channel": d.get("author_name", ""),
                     "channelUrl": d.get("author_url", "")}
        print(f"ok   {vid}: {meta[vid]['title']}")
    except Exception as e:  # noqa
        print(f"fail {vid}: {e}", file=sys.stderr)

out = ("/* Generated by tools/fetch_titles.py from YouTube oEmbed. Do not edit by hand. */\n"
       "window.TRACK_META = " + json.dumps(meta, indent=2, ensure_ascii=False) + ";\n")
(root / "track-meta.js").write_text(out)
print(f"wrote track-meta.js ({len(meta)}/{len(ids)} tracks)")
